project:
  type: website
  output-dir: docs

website:
  title: "SenS"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Second page
      - href: third.qmd
        text: Further details

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



